# Fonts
font_family                     JetBrainsMono NFM Regular
bold_font                       auto
italic_font                     auto
bold_italic_font                auto
font_size                       13.0
disable_ligatures               cursor
modify_font                     underline_position 0
modify_font                     underline_thickness 140%
modify_font                     strikethrough_position 2px
modify_font                     cell_width 100%
modify_font                     cell_height 1px
modify_font                     baseline 0
box_drawing_scale               0.001, 0.5, 1.5, 2
undercurl_style                 thin-sparse
text_composition_strategy       platform
text_fg_override_threshold      0

# Cursor
cursor_shape                    underline
cursor_shape_unfocused          hollow
cursor_beam_thickness           1.5
cursor_underline_thickness      2.5
cursor_blink_interval           -1
cursor_stop_blinking_after      0

# New feature
cursor_trail                    1
cursor_trail_decay              0.1 0.9
cursor_trail_start_threshold    2
# cursor_trail_color              #94E2D5

# Scrollback
scrollback_lines                3000
scrollbar                       scrolled
scrollbar_jump_on_click         yes
scrollbar_width                 0.8
scrollbar_hover_width           1.2
scrollbar_handle_opacity        0.2
scrollbar_radius                1.0
wheel_scroll_multiplier         7.0
touch_scroll_multiplier         7.0
# NOTE: Required NVIM 0.12
# scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -

# Mouse
mouse_hide_wait                 -1.0
url_style                       curly
copy_on_select                  yes
strip_trailing_spaces           smart
focus_follows_mouse             yes
pointer_shape_when_grabbed      beam
default_pointer_shape           arrow
pointer_shape_when_dragging     beam crosshair

# Performance
repaint_delay                   10
input_delay                     3
sync_to_monitor                 no

# Window layout
remember_window_size            no
initial_window_width            1790
initial_window_height           1002
window_resize_step_cells        0
window_resize_step_lines        0
window_border_width             1pt
draw_minimal_borders            yes
window_margin_width             0
single_window_margin_width      -1
window_padding_width            0
placement_strategy              center
active_border_color             #888888
inactive_border_color           #444444
inactive_text_alpha             0.8
hide_window_decorations         yes

# Tab bar
# tab_bar_edge                    top
tab_bar_style                   hidden
# tab_bar_align                   center
# tab_bar_min_tabs                2
# tab_title_max_length            0
# tab_separator                   " "
# tab_title_template              "  {'/'.join(tab.active_wd.split('/')[-1:])}{sup.index} "
# active_tab_title_template       " 󰄫 {title.split(' ')[0]}{sup.index} "
# active_tab_font_style           bold
# inactive_tab_font_style         nobold

# Color Theme
# background_opacity              0.98
# background_blur                 1


# Advanced
shell                           /usr/bin/fish
shell_integration               enabled no-cursor no-cwd

# OS specific tweaks
# wayland_titlebar_color          system
linux_display_server            wayland
wayland_enable_ime              no
